//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventInfoes = new HashSet<EventInfo>();
        }
    
        public System.Guid EventId { get; set; }
        public System.Guid UserId { get; set; }
        public string EventName { get; set; }
        public byte[] EventNameHash { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<EventInfo> EventInfoes { get; set; }
    }
}
