//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInfo
    {
        public System.Guid EventInfoId { get; set; }
        public System.Guid EventId { get; set; }
        public string EventOwner { get; set; }
        public string EventDescription { get; set; }
        public string EventLocation { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
